### ISSUE TITLE
Support --console rich on console output

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#107]
With --console rich the eclipse console output shows control chars etc.

Instead of highlighting  keywords, defined inside EGradle it would be a nice approach to handle 
ANSI control chars instead, so we would get improved output and in such colors gradle think being important.

see https://docs.gradle.org/current/userguide/gradle_command_line.html (--console)

**Comment by de-jcup** [comment]
There exists an ANSI eclipse console plugin:
http://mihai-nita.net/2013/06/03/eclipse-plugin-ansi-in-console/
https://github.com/mihnita/ansi-econsole/blob/master/AnsiConsole/src/mnita/ansiconsole/participants/AnsiConsoleStyleListener.java

It only supports colouring, but no cursor movement etc.

It seems the only way to do this, would be to implement a view, which is feed by EGradle style listener with extra data. Eclipse standard console output seems not to be possible with cursor movement.

But cursor movement is used extremely by gradle in rich console mode!

**Comment by de-jcup** [comment]
This would solve the problem of long running gradle builds - shows its not a zombie process...

**Comment by paulvi** [comment]
Why not just create an issue like https://github.com/mihnita/ansi-econsole/issues/24

**Comment by de-jcup** [comment]
Hmm.. another idea would be to add (only on egradle console parts) a progress view part where the updating text (cursor movement) is done standalone. So simple coloring could be done as same way as done in ANSI eclipse conosle plugin (or ignored) and the cursor movement parts etc. would happen the progress view
