### ISSUE TITLE
`fileExtension_gradle` tag on marketplace 

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#116]
EGradle now has editor https://github.com/de-jcup/egradle/tree/master/egradle-plugin-gradle-editor

on marketplace add `fileExtension_gradle` tag, so EGradle will be suggested by Eclispe IDE is user has not yet associated editor.

see https://marketplace.eclipse.org/content/minimalist-gradle-editor for example

ref #49

**Comment by de-jcup** [comment]
Thanks a lot for the tip!

**Comment by de-jcup** [comment]
Done at marketplace
