### ISSUE TITLE
EGradle editor outline view

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#119]
Sometimes it would be nice to have an outline view - e.g. when build scripts are too big (and nobody uses includes...) 

At least the main parts should be shown( e.g. tasks) . A problem is the groovy syntax which provides multiple ways to define. Maybe there is a simple groovy/gradle parser available. Otherwise I will write a simple appraoch by myself - it should be not too much difficult

Work to do:

- [x] Create a outline view
- [x] Create a fast position mapping (offset -> next possible token in xyz)
- [x] Provide Linking with editor as done on java editor:
   - [x] Provide "Link with Editor" option in outline view
   - [x] No "Link with Editor": double click on outline part selects corresponding part in editor
   - [x] "Link with Edtior": caret changes in editor, so outline selection changes - if other token
   - [x] "Link with Editor": single click on outline part selects corresponding part in editor
- [x] Enhanced Label decoration (own icons, improved text)
- [x] Shrink groovy-all dependency to necessary parts

**Comment by de-jcup** [comment]
Outline begins to work: current state:

![egradle-outline-1](https://cloud.githubusercontent.com/assets/11644753/19912785/6f5a1834-a09d-11e6-889e-a9893dba7f91.png)

**Comment by de-jcup** [comment]
Token parser works now pretty good.
Outline simply shows tokens and their children. Positions/Offset calculation of parser works.
![egradle-outline-view-6 11 2016](https://cloud.githubusercontent.com/assets/11644753/20042386/72214d0a-a479-11e6-8fd2-7c2f6de49cff.png)

**Comment by de-jcup** [comment]
Hmm. groovy.jar contains Parser.groovy which is using the GradleLexer etc. 

I tried out to use the groovy parser. The API is .... a little bit ugly... and I do not know  if the offset position handling is correct. But I give it a try. 

One benefit is that compile errors an be done easily checked. So at least the editor could get a clean validation possibility.

One problem remaining is the access to groovy.jar. Either I depoy EGradle with a groovy.jar (its apache so no problem) another option would be to use the groovy executed by gradle. (which would produce same error output as on gradle execution...).

**Comment by paulvi** [comment]
gradle DSL can be treated as language on its own. Aproaching it as superset of Groovy would lead to as heavy dependency and complexity as using Gradle integration API

For Minimalist Gradle Editor, i did own parser that only tried 

- to find matching brackets,
- take note of predefined list of words
That would be limited, but super fast.

Other idea was go with antlr4 to define grammar. Not tried.

**Comment by de-jcup** [comment]
@paulvi  : Hello Paul, my own token parser works very well now, but to show correct outline information the tokens must be scanned and statements build (e.g. for defined variables, methods etc.) And this is really much work.

I sneaked a little bit to IntelliJ and did recognize they seem to use gradle jdk (they do often reuse existing and productive stable parts - e.g. eclipse compiler... or even the eclipse source code formatter (optional) ). So I started to think about how does groovy the job of parsing.

After a little inspection I found working antlr parts of Groovy it self which is token based, and very fast, but supports already type, modifier recognition etc.

So in branch "feature-119-groovy-outline" a  branch of "feature-119-editor-outline"  i am trying out the possibilities groovy-all.jar gives. The gradle dsl itself has to be handled special of course, but using the gradle antlr parts you are able to identify commands like "task" directly in code, in a very easy (and correct) way! The first approach looks interesting.

When it really works, I am thinking about shrinking necessary parts to e.g. groovy-reduced.jar where only the necessary parser parts will exist.. Currently there are parts missing (e.g. correct offset calculation for eclipse )which I already did in my own token parser implementation.

When the groovy appraoch does not work well, or it will be too much heavy, I will fall back to my own implementation. But if it works, i will reduce much work for myself (and errors...). 

Also the usage of Groovy could provide validation feature for editor as well (simple groovy failues can be shown without call of gradle command). And maybe a simple code completion would be no hard work any more... Also syntax highlighting could be done more correct (fields/variables could have special  colouring etc.)

**Comment by de-jcup** [comment]
An outline view screenshot of last commit...
![egradle-screenshot-outline-2016-11-13](https://cloud.githubusercontent.com/assets/11644753/20249451/99e38bd4-a9f9-11e6-9145-d4fc648f3407.png)

**Comment by de-jcup** [comment]
Feature now stable, merged into master.

**Comment by paulvi** [comment]
Hooray, looks awesome
