### ISSUE TITLE
Enhance quick outline

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#134]
A "CTRL + O + O" shall build a temp big file and show its outline - same behaviour as on java editor quick outline...

To be done after:
#133 
#122

**Comment by de-jcup** [comment]
ModelBuilder must build items containig information about linked files, so can be opened by editor...

**Comment by paulvi** [comment]
- [ ] wiki does not mention this feature yet https://github.com/de-jcup/egradle/wiki/Features

**Comment by de-jcup** [comment]
Hello @paulvi : The wiki contains always only features which are available/implemented/merged at least to master and so will be inside next release. Currently quick outline #122 is  implemented on its own branch and development is not done. I always check issues done in Milestones for current release and update documentation + wiki before release is done.

 _(and I had a type inside upper comments - I said "To be done before..." - changed it to "Implementation can be started after:")_

**Comment by de-jcup** [comment]
Sorry not enough time - will close this issue.
