### ISSUE TITLE
[low priority] Make parser as separate module

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#135]
As started in https://github.com/de-jcup/egradle/issues/119#issuecomment-259644222

could you make your parser as separate module, or in other words simpler for reuse

Note: I don't have plans to actually use it within coming month

![](https://cloud.githubusercontent.com/assets/11644753/20249451/99e38bd4-a9f9-11e6-9145-d4fc648f3407.png)

**Comment by paulvi** [comment]
Also possibly share antlr grammar in https://github.com/antlr/grammars-v4

https://github.com/antlr4ide/antlr4ide/issues/141

**Comment by de-jcup** [comment]
Hello @paulvi : The egradle core parts could be provided to maven central as a kind of lib containing "src/main/java" and "src/main/java-groovy". So it could simply be used as a library + antlr as an dependency.  Currently its not ready (and not well documented for api usage outside egradle...)

But... the antlr parts are still plain groovy anltr! 

Look into 
https://github.com/de-jcup/egradle/blob/master/egradle-other/src/main/java/de/jcup/egradle/other/GroovyParserSourceCollector.java

which contains information about how i got antlr + groovy working . In a nutshell: I reused the existing antlr parts from apache groovy project and generated antlr parts by myself. I copied the generated parts and some necessary groovy classes into my project. So it is not really "my parser". This is also the reason why I used "src/java-groovy" as dedicated source folder, so its clear it comes originally from apache groovy project and I did also not change package declartions or something in code there.

The outline model is written by myself. It is simply build my GradleModelBuilder which is enough for outline handling - it setup some gradle item types to identify wellknown parts and it does know closures - which will be always rendered by green lines icon. But it is far away from being a real gradle parser.

https://github.com/antlr/grammars-v4 does not contains groovy - but the grammer can be found at the apache groovy page (somewhere)

Are you still interested in having my approach as a library?

**Comment by paulvi** [comment]
> Note: I don't have plans to actually use it within coming month

That is actually not right now.

**Comment by de-jcup** [comment]
Sorry about asking again - but : Are you still interested in having my approach as a library?

**Comment by paulvi** [comment]
me personally not, as I am not going to work on plugins for Gradle again

**Comment by de-jcup** [comment]
Ok. So I will focus on making the editor usable by other plugins as you suggested in #136 . Its planned for Version 1.2
