### ISSUE TITLE
Editor becomes separate feature

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#136]
Currently Editor is baked into EGradle

https://github.com/de-jcup/egradle/blob/master/egradle-feature/feature.xml#L108

**Comment by de-jcup** [comment]
@paulvi : Would you like to have EGradle installable standalone from eclipse market place?

**Comment by paulvi** [comment]
That would be offline installing using update site zip file.

With this #136 issue EGradle Editor can be used without EGradle. E.g. in https://marketplace.eclipse.org/content/gradle-ide-pack

**Comment by de-jcup** [comment]
There are some dependencies to be cleaned up and I am still stuck with the quick outline feature for EGradle 1.1.0 but I assigned it to myself and will give it a try.

**Comment by paulvi** [comment]
up

I wonder could editor be used with Eclipse Buildship, so that it could be recommended as the only and the best Editor, and I would OUTDATE my Minimalist Editor

**Comment by de-jcup** [comment]
Hello @paulvi, 

Thank you... :-) 

### Current situation:
At current version (1.2.1) it should be possible to install EGradle and Buildship parallel and use only the EGradle Editor. 

### Planning:
With release 2.0 - which will come... the editor will be usable from other IDEs. To enable this, I will do following:

- introduce another plugin called "egradle-plugin-ide"
- make "egradle-plugin-main" be the "core" - module
- let integrate "egradle-plugin-ide" all IDE stuff from egradle which is not necessary when using
  another IDE
- refactor namings, so most parts will become "internal" package name parts, so its clear its not an 
  official API
- provide extension points for other IDEs to 
  - integrate launch mechanism to outline view 
  - support variable resolving (root folder etc.)
  - ... to be continued 
- move EGralde main preference page to a sub page
- update eclipse help (maybe divide editor and IDE or make just an hint in documentation)
- create own standalone feature for editor
- publish "EGradle IDE" and "EGradle Editor"

**Comment by de-jcup** [comment]
- [ ] Seperate main into a core and ui /ide project + update references etc.
- [ ] Make own editor feature

**Comment by paulvi** [comment]
I am not using gradle for last few month, so I will just follow when this ticket is closed.

You already publish to bintray, don't you?

**Comment by de-jcup** [comment]
@paulvi : yes, I already publish to bintray

**Comment by de-jcup** [comment]
@paulvi  EGradle 2.0 was released today.  Editor is now a separate feature. Its binary can be found inside
EGradle update site on bintray.

I also started an own marketplace page for the editor at https://marketplace.eclipse.org/content/egradle-editor .
