### ISSUE TITLE
Support Android DSL

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#155]
Just in case you haven't looked, DSL is at http://google.github.io/android-gradle-dsl/current/

**Comment by de-jcup** [comment]
Sorrowly android is not part of the official plugins supported by gradle itself
so the generated dsl files do not include it.

http://tools.android.com/build
describes how to get sources of android plugin

If supporting this DSL there are following options:
- [ ] reuse the former XMLProposal approach (now in egradle-draft) and provide custom xml files ( not good)
- [ ] use origin files and generate addtional xml files which can be contributed to parts created for gradle
- [ ] ... to be continued

**Comment by de-jcup** [comment]
https://bintray.com/android/android-tools/com.android.tools.build.gradle#files/com/android/tools/build/gradle/2.3.0-beta3

contains the origin sources! So if SDK generator would no longer use the gradle approach but has an own implementation for scanning sources and generating, it would be relative simple to obtain data.

**Comment by paulvi** [comment]
From https://github.com/google/android-gradle-dsl

> For instructions on how to check out the plugin source code, see the Building the Android Gradle Plugin page.

http://tools.android.com/build/gradleplugin

Did you need sources?

**Comment by de-jcup** [comment]
Hello @paulvi , the bintray link contains full sources. The gradle plugin sources under
http://tools.android.com/build/gradleplugin sources are complete bundled with android studio.

Maybe the bintray source parts should do enough. But thank you.

Gradle on groovy has the problem that it's often not clear what the closure is executing. It makes you crazy when you have no real reliable information about this. Even the origin gradle compiler does not resolve the type completely etc. But the delegation target information is normally only contained inside the javadoc. So the Gradle DSL type estimator developed in #120  does use information from EGradle-SDK which is created by an SDK builder (which uses a gradle branch and its generated doc...)  which inspects javadoc parts too...

But maybe its much easier with a normal plugin - I currently do not know.

The current #120 developed SDK is compatible with Gradle 3.0 and is working good at the moment. 
It is used for code completion and also for code tooltips:
![image](https://cloud.githubusercontent.com/assets/11644753/22991534/d7b252e4-f3bc-11e6-9a00-b1e4c142d628.png)

I am concentrating on #120 currently. Inside SDK there are generated xml definitions for model, so it should be very easy to adopt plugins like "android" into the generated sdk as well.

**Comment by de-jcup** [comment]
I am sorry. Have to less time for this. close it now
