### ISSUE TITLE
Update site location

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#159]
2.5 years ago I compared GitHub/SourceForge/Bintray speed for update site

http://www.nodeclipse.org/nodeclipse/binaries/bintray/2014/05/09/Nodeclipse-on-Bintray.html

The numbers may be different today or for your location, but hopefully you can find time to check/decide

**Comment by de-jcup** [comment]
- [ ] Check if this is still necessary (or github is fast enough)

Maybe use lars approach:
https://github.com/vogellacompany/bintray-publish-p2-updatesite/

**Comment by de-jcup** [comment]
Changed update site to https://dl.bintray.com/de-jcup/egradle/

**Comment by paulvi** [comment]
Not that with bintray, you can't change published files.
