### ISSUE TITLE
[minor] Activate or link to activate console on error

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#162]
This dialog should have link to activate console 

![image](https://cloud.githubusercontent.com/assets/1614482/21101989/e9fe3302-c0b6-11e6-8fee-582e5d9933c9.png)

**Comment by paulvi** [comment]
Similar should be for 

![image](https://cloud.githubusercontent.com/assets/1614482/21102498/71428ae6-c0b9-11e6-848f-5c5cbc76db3d.png)

**Comment by de-jcup** [comment]
- Before Build failed dialog appears now console view is shown (behaviour is changeable in preferences, default is true)
- Import failed does now always show up system console before fail dialog appears.
