### ISSUE TITLE
dark color themes are barely usable

### ISSUE THREAD

**Issue by chadj2** [de-jcup/egradle#163]
Before installing egradle I was using a dark text editor theme with the eclipse color theme editor. 

When I installed egradle the text in the editor was barely readable because some of the dark text colors that work with a bright theme did not change in contrast to the background. I tried to manually change these colors in the editor but I was not able to. 

The bright theme is harsh on my eyes and I can't use egradle until it either uses the system colors from the themes or it allows me to manually change colors.

**Comment by de-jcup** [comment]
Hello @chadj2 at #118 I was inspecting the moon rise theme.
hm.. when I look inside the pictures at #118 I see also the problem... 

I will fix this with #118 in upcoming release (probably version 1.1.5).

**Comment by chadj2** [comment]
While fixing this please also have a look at the eclipse color theme:
https://marketplace.eclipse.org/content/eclipse-color-theme

This is the #2 most popular download on eclipse marketplace. The utility offers many different themes specifically for text editors. Most of the eclipse editors use system colors that are updated by the themes.

**Comment by de-jcup** [comment]
@chadj2 : Version 1.2 will come in next days (probably friday). It will have the changes done in #118 .
Your suggestion of supporting https://marketplace.eclipse.org/content/eclipse-color-theme will be handled with #167 which will be done later.

**Comment by de-jcup** [comment]
@chadj2 - just released version 1.2.0 at eclipse marketplace - contains bugfix :-)

**Comment by chadj2** [comment]
I appreciate it! I will have a look.
