### ISSUE TITLE
Update icon from gradle distribution

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#164]
gradle distribution comes with set of icons

**Comment by de-jcup** [comment]
~/.gradle\wrapper\dists\gradle-3.1-bin\37qejo6a26ua35lyn7h1u9v2n\gradle-3.1\media
Apache 2.0 License,
contains origin gradle icons

@paulvi  thanx a lot

**Comment by de-jcup** [comment]
Using now media part from gradle dist as suggested - see #118
