### ISSUE TITLE
Outline do not show all entries

### ISSUE THREAD

**Issue by wolfgang-ch** [de-jcup/egradle#171]
When this files https://github.com/diffplug/gradle-and-eclipse-rcp/blob/master/build.gradle is opened in the eclipse editor, then the outline misses some entries, e.g. all which are in `configure(subprojects...`

![egradle-outline-problem](https://cloud.githubusercontent.com/assets/1283445/21306501/93ef9f30-c5d1-11e6-9e65-09ddfd1eb98b.png)

**Comment by de-jcup** [comment]
Hello @wolfgang-ch Bugfix is done, comes with Version 1.2.1 in the next days. Outline is also much improved, shows now assignments as well + parameters etc.

**Comment by de-jcup** [comment]
@wolfgang-ch : Version 1.2.1 is released with bugfix.

**Comment by de-jcup** [comment]
Hello @wolfgang-ch 
Version 1.2.1 is released and contains your bugfix. If you have problems with update (like myself) you can use the new update site: https://dl.bintray.com/de-jcup/egradle/
