### ISSUE TITLE
Update-Site location in feature.xml wrong

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#181]
feature.xml files do contain old  site url 
Must be changed to
https://dl.bintray.com/de-jcup/egradle/ 

But works with new site too. So not urgent

**Comment by paulvi** [comment]
actually URL there is not used anywhere

ref #159 #184

**Comment by de-jcup** [comment]
Thanks @paulvi , even when not used, I think its better when I remove the URL in next release.
