### ISSUE TITLE
Outline comfort feature

### ISSUE THREAD

**Issue by wolfgang-ch** [de-jcup/egradle#183]
Expand/collapse tree entry with

- single click (which currently navigates to the item in the editor) 
AND/OR
- double click

I know, some people like or dislike it, then an option could solve this but then it needs more time to implement it.

**Comment by de-jcup** [comment]
Hello @wolfgang-ch , is there any other view doing this in a similar way as you described?
Hmm.. maybe when the editor is linked with outline and so the double click is not used, it could do unfold the selected tree entry.

**Comment by wolfgang-ch** [comment]
**Example for expanding a treeitem**
In my app in the pref dialog when you double click a root item, e.g. Speed, then this item is expanded and others are collapsed, so this is more than I've requested. Instead of double click you can implement it also for a single click.

The code is here
https://github.com/wolfgang-ch/mytourbook/blob/master/bundles/net.tourbook/src/net/tourbook/preferences/PrefPageAppearanceColors.java#L308

![pref-chart-color](https://cloud.githubusercontent.com/assets/1283445/21422160/c1f6394a-c836-11e6-8185-16a26330b4ef.png)

**Comment by de-jcup** [comment]
Ok. nice. 

how urgent is this feature for you?

**Comment by wolfgang-ch** [comment]
Yesterday :-)

No, is not urgent, much more importantly would be this https://github.com/de-jcup/egradle/issues/120 and https://github.com/de-jcup/egradle/issues/178 because Gradle/Groovy is new to me, when I find an unknown item in the gradle file, I have to google for it instead of just reading the tooltip.

**Comment by de-jcup** [comment]
OK. Will try to implement it with 2.0

**Comment by de-jcup** [comment]
Hello @wolfgang-ch 
I found out that you if you select an collapsed tree node in eclipse (neon) you simply can press "multiply" (x) on numeric pad and it will collapse the complete node. 

This works for every node in every tree view !

See : http://stackoverflow.com/questions/12471682/in-eclipse-package-explorer-how-can-i-expand-a-tree-in-one-click details at _(Numpad_Multiply)_

It can be configured in preferences:
![image](https://cloud.githubusercontent.com/assets/11644753/25277689/0aa9d2a6-26a0-11e7-9bc1-f799f602ecff.png)

In my opinion eclipse does this already pretty good (but it's not well documented). So I think I will not implement an addititional tree behaviour (sorry).

But to have this with not only a key but also with mouse events, I created following feature request :
https://bugs.eclipse.org/bugs/show_bug.cgi?id=515577
"Command binding not only with keys but also with Mouse-Events"
where you could always bind the operations  (and also of custom plugins) to mouse events  - so you could configure this for all of your tree views.

Please vote for the eclipse issue if you like it.
