### ISSUE TITLE
Composite site

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#184]
A bad side of Bintray is that files can't be changed.

That makes every release having new URL.
The solution may be p2 Composite site

ref #159

**Comment by de-jcup** [comment]
Hi @paulvi - hm. Not able to change site.xml would not be good good (at least you can't do this at UI)

But there are possibilities:
- You can upload to another version  in your bintray package. 
  https://bintray.com/de-jcup/egradle/update-site/current  - my version is called "current"
   (repo/package/version)  - the URL is always the same : https://dl.bintray.com/de-jcup/egradle/
  So I can upload to a new version - e.g. "1.3" , then delete old verson ("current") and publish new version.
- Another option would be to use the gradle plugin for bintray - it seems its able to replace version files parts, see https://github.com/bintray/gradle-bintray-plugin/issues/77

**Comment by de-jcup** [comment]
I will have to update the script used by EGradle to supply override=1 for site.xml and conten.jar.

**Comment by de-jcup** [comment]
It seems the easiest way would be to use asimple 

`PUT /content/:subject/:repo/:file_path `

without any versioning

**Comment by paulvi** [comment]
yes, my knowledge was outdated. 
It is possible to update, so there is no need to have composite site

**Comment by de-jcup** [comment]
It seems to work correct with bintray. So closed issue
