### ISSUE TITLE
EGradle Editor: improve dark theme default colors

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#185]
At least task default color is not working (linux , dark theme). Its too dark.

**Comment by ncorai** [comment]
Same problem in Windows 10, Neon.2, Dark Theme w/ Default (current):
All the colors seem designed for a white background and make reading text in EGradle really difficult.

**Comment by de-jcup** [comment]
Hello @ncorai ,

EGradle (current 1.2.1) supports custom colors and special defaults for dark theme, but you must
apply the special defaults in preferenes - please look at:
https://rawgit.com/de-jcup/egradle/master/egradle-plugin-main/html/user_guide/editor.html#syntax_highlight_dark_theme_defaults

You can customize the colours by your own as shown in link. The issue listed above is only about the default "Gradle task keywords" for dark theme which is a little bit too dark.

**Comment by ncorai** [comment]
Indeed, I wasn't looking for custom colors outside the `General->Appearance->Colors and Fonts` section, but you do mirror the JDT preferences (although they manage to switch automatically when the theme changes, but I recognize the whole theming thing in Eclipse is a mess).

So, thanks for your help, and apologies for the noise on the thread.

**Comment by de-jcup** [comment]
Done with #229
