### ISSUE TITLE
Installation new gradle binaries by gradle wrapper does result in a timeout

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#209]
Using egradle importer with gradle wrapper which is not already downloaded results in a time out!

This should be already fixed with #127 , but appeared
with egradle on linux again when importing gradle fork !

Ideas: What about making the timeout configurable? Or turnable off ?

**Comment by luksrn** [comment]
Hi,

I'm having this problem when new developers need to import the project for the first time. It would be interesting to configure the timeout in the preferences of the plugin.

![image](https://cloud.githubusercontent.com/assets/698313/23910795/a2526b9a-08b9-11e7-8990-b5b7205248f8.png)

**Comment by de-jcup** [comment]
Hello @luksrn ,

I will try to fix this problem with upcoming EGradle version 1.3:

1. At least make the timeout configurable (for those operations which have timeouts at all - there are many operations inside EGradle which have endless, means 0 seconds, time already set).

2. Try to identify why the former fix does not solve the problem / are outputs reseting terminator instance.
    Normally every output done in console will reset the time out terminator instance.


> I tried to import the same project - after removing the .gradle folder - through windows and didn't get the same error

Hmm... The timeout seemed to happen between "cleanEclipse" and "eclipseClasspath" - relying on output in console. So gradle seems to do an operation there which is long running there  - I think this could be dependency resolving etc. When deleting the .gradle folder this is like a "hard dependeny resolution reset" because it will delete all cached information. So maybe next start did perform just a little bit faster than before and was under 30 seconds.

**Comment by de-jcup** [comment]
Hello @luksrn ,

Changed behaviour of import completely: 
With implementation done for #132 the import operation is now canceable and has no longer a need for a time out. The time out is completely removed for import mechanism.

**Comment by luksrn** [comment]
@de-jcup Amazing! I didn't expect that this fix would be so fast. When the new version will be avaliable on eclipse market place? Thanks again!

**Comment by de-jcup** [comment]
@luksrn You are wellcome. The bug also bothered me ...

I have to document all the changes (see https://github.com/de-jcup/egradle/milestone/19?closed=1) inside documentation and do some other stuff (see https://github.com/de-jcup/egradle/issues/216), so I think Version 1.3.0 will be available in market place in 1-2 weeks. 

I will do announce new released versions always by https://plus.google.com/u/0/collection/s8j0ME so you can follow if you like. There exists also an RSS feed at eclipse market place.

**Comment by de-jcup** [comment]
@luksrn : EGradle 1.3.0 is now released and contains the fix.

**Comment by luksrn** [comment]
thank you @de-jcup! I'm already using the new version!
