### ISSUE TITLE
Cosmetic but better UI

### ISSUE THREAD

**Issue by wolfgang-ch** [de-jcup/egradle#252]
Enlarge the validation log by grabbing the whole vertical space.

![e-gradle-pref](https://cloud.githubusercontent.com/assets/1283445/25650106/e4ed6f02-2fda-11e7-95a3-96c9945c0aac.png)

**Comment by wolfgang-ch** [comment]
submitted pull request https://github.com/de-jcup/egradle/pull/254

**Comment by de-jcup** [comment]
Thank you wolfgang. 
Works fine, is merged to master, comes with upcoming 1.3.1.
