### ISSUE TITLE
Default Shortcut ctrl+shift+# hardly usable on US keyboard

### ISSUE THREAD

**Issue by midnightghost** [de-jcup/egradle#265]
On US keyboard layout the #-symbol is on "Shift+3". Therefore you would have to enable caps lock to use the default shortcut for "Quick gradle task execution". 

Key mapping from german layout to us layout is: # == \. Means: On US layout the backslash is at the position where the german hashtag is. 

BTW: Ctrl+Shift+End also seems to be unused in default eclipse installation. Furthermore "End" should always be at the same position on every keyboard. Might be worth a thought to change it completely to Ctrl+Shift+End?

**Comment by de-jcup** [comment]
Hi Tim, I appreciate your idea about using "CTRL + SHIFT + END" instead of "CTRL + SHIFT + #". But there could be some people already using "CTRL + SHIFT +#". So I will support both short cuts with EGradle 2.0.
