### ISSUE TITLE
Emacs setting in Window->Preferences not respected

### ISSUE THREAD

**Issue by kurtg123** [de-jcup/egradle#289]
I just updated to oxygen, so I noticed that it doesn't respect the Emacs setting in Window->Preferences->General->Keys when changing scheme to Emacs.    

Also, just an annoyance, but when opening a "{" it would be great if it also inserted a newline (maybe as an option).   I'm trying to get use to having the closing bracing pestering me, but I usually just hit return a few times and then re position my cursor.

**Comment by de-jcup** [comment]
I will change the title to "Emacs problems" because the "Opening "{" ... parts are defined in #290 (so duplicated + #290 will be done with milestone 2.1.1).

**Comment by de-jcup** [comment]
Hello @kurtg123 ,  I do not understand your question about the Emacs settings.
When I open the settings you are able to define EGradle parts in Emacs settings as well:
![image](https://user-images.githubusercontent.com/11644753/30199244-257da270-9472-11e7-9aad-4c8f51f3890e.png)

Or would you prefer other defaults on Emacs settings? Maybe this would be possible but I have no Idea what would be the appropriate ones... So please explain - and if you got some preferences for emacs setup please tell me.

**Comment by de-jcup** [comment]
Having a long time no repsonse I close this issue.
