### ISSUE TITLE
Request: Opening "{" also provides a newline before the "}"

### ISSUE THREAD

**Issue by kurtg123** [de-jcup/egradle#290]
Also, just an annoyance, but when opening a "{" it would be great if it also inserted a newline (maybe as an option).   I'm trying to get use to having the closing brace pestering me, but I usually just hit return a few times and then re position my cursor.  Needless to say, I rarely do a one-liner. 

Otherwise, I love the editor.   I'll try getting my work to approve the editor.

**Comment by de-jcup** [comment]
I will try to change the template mechanism here. Should be default because most people use

```
xyz{
   somesettings=true
}
```
instead of 
xyz{ somesettings=true}

Will come with version 2.1.1

**Comment by de-jcup** [comment]
`xyz{ `works now correct,
, but
`xyz {`
comes out a little bit ugly, so there is still some work ...

**Comment by de-jcup** [comment]
With this issue a support for [ ] was also introduced , but not multi lined but single line as before for {
So typing `a = [` will result in `a = [ $cursor ]`
