### ISSUE TITLE
Editor for Jenkinsfile - refactor EGradle and provide groovy parts for Jenkins Editor

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#291]
Jenkins 2 introduced pipeline and groovy-based DSL for definition,
and recently second declarative syntax

https://jenkins.io/doc/book/pipeline/  
https://jenkins.io/doc/book/pipeline/syntax/

```groovy
node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/jglick/simple-maven-project-with-tests.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'Maven_3.5.0'
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }
}
```

and  declarative example

```groovy
pipeline {
    agent any 

    stages {
        stage('Build') { 
            steps { 
                sh 'make' 
            }
        }
        stage('Test'){
            steps {
                sh 'make check'
                junit 'reports/**/*.xml' 
            }
        }
        stage('Deploy') {
            steps {
                sh 'make publish'
            }
        }
    }
}
```

I can possibly do myself, based on cloned Minimalist Editor https://github.com/Nodeclipse/GradleEditor,
but if you care your one may be better.

So raising this ticket for our conversation, and some extra notes.

**Comment by paulvi** [comment]
Besides Editor, there is also possible to use external Linter   
https://jenkins.io/doc/book/pipeline/development/#linter

e.g. run it by right-clicking Run

**Comment by de-jcup** [comment]
@paulvi Let me see what I can do. 

I have already created a new repository at https://github.com/de-jcup/eclipse-jenkins-editor . The editor will reuse egradle parts (needs some refactoring inside egradle to make groovy parts better accessible) so it should be easy to adopt it - with an own DSL description even code assistence should be not much effort (maybe).

**Comment by de-jcup** [comment]
Refactored EGradle inside special feature branch by commit https://github.com/de-jcup/egradle/commit/c7e9c11e9b26b6d07a1cf25924b10c0fc3027099 so initial commit https://github.com/de-jcup/eclipse-jenkins-editor/commit/93ed9dd8f62d29c3a014def76f4edbad82a4b371 starts to work (minimal outline, full groovy support, but many parts still missing)

**Comment by de-jcup** [comment]
@paulvi Its nearly done:
As you can see the refactoring is bringing "Jenkins Editor" to live:
![image](https://user-images.githubusercontent.com/11644753/30989858-843fd868-a49f-11e7-9a13-15b7be2406ad.png)

Working with 0.2.0:
- Simple auto validation of gradle code
- Outline (simple)
- Quickoutline
- Bracketswitching
- Syntax highlighting
- Block commenting

I will close now this ticket - after deployment of EGradle 2.2.0 I will also deploy Jenkins Editor 0.2.0 (beta) to eclipse market place (Jenkins Editor uses egradle-main-plugin for groovy parts...)

Keep track on my closing of https://github.com/de-jcup/eclipse-jenkins-editor/issues/2 so Jenkins Editor will be available... :-)

**Comment by paulvi** [comment]
finished quicker than I was ready to comment...
