### ISSUE TITLE
pom.groovy Editor

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#296]
Maven uses groovy via Polyglot maven

ref Editor for Jenkinsfile #291

@jdillon

**Comment by de-jcup** [comment]
@paulvi 
Sorry but I did not cached what the issue shall do

You already can open pom.groovy with EGradle:

![grafik](https://user-images.githubusercontent.com/11644753/31037279-790f2bfc-a570-11e7-8169-eb383764ce30.png)

**Comment by paulvi** [comment]
oh, 

- [ ] (minor) is Editor already associated with .grooyy extension?
- [ ] (minor) Maven pom has some standard elements like `build`, that should be shown as main bold section
