### ISSUE TITLE
missed comma

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#297]
missed comma in dialog

![image](https://user-images.githubusercontent.com/1614482/31237410-7948ca98-aa29-11e7-84df-7c954c542d4d.png)

Suggesting

"Please enter group name (project name by default)"

**Comment by paulvi** [comment]
Or just have Project name there already, with text selected, so any typing would clean this default.

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/31816931-7b71c0e4-b592-11e7-8bf8-f43db28e377b.png)

Project name is now the message of text field. So whenever user enters text the message disappears, but will return when entered text is cleared again...

**Comment by paulvi** [comment]
Usually instead of message, there is default text in field (all selected), that can be edited or deleted when user starts typing.
