### ISSUE TITLE
What is derived?

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#298]
New user has no idea what this would mean

![image](https://user-images.githubusercontent.com/1614482/31237558-e64b8b44-aa29-11e7-816b-6aecf338fe92.png)

**Comment by de-jcup** [comment]
https://rawgit.com/de-jcup/egradle/master/egradle-plugin-main/html/user_guide/filehandling.html

Does describe the feature. So if there are people having problems with this feature they just have to read the documentation /help.

**Comment by paulvi** [comment]
Also found at https://stackoverflow.com/questions/4849173/what-are-derived-files-in-eclipse

What about UI to be
"

- [ ] set build folders automatically to be "derived"  
(every call of `Refresh eclipse dependencies` and also
`EGradle imports` will automatically set gradle build folders as "derived")

(clickable link to built-in manual)  
"

Also see http://nodj.github.io/AutoDeriv

**Comment by paulvi** [comment]
There is also plugin specially for handling derived property. https://marketplace.eclipse.org/content/autoderiv

Configuration via `.derived` file http://nodj.github.io/AutoDeriv/
