### ISSUE TITLE
Gradle root project in Preferences

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#299]
I think it is just wrong to have Gradle root project in Preferences,
as it is should be property of a project in workspace, not setting for whole workspace.

![image](https://user-images.githubusercontent.com/1614482/31237688-3e078928-aa2a-11e7-878f-2f43d578d1c3.png)

What about case with 2 multimodule projects in the same workspace?

**Comment by de-jcup** [comment]
Same as https://github.com/de-jcup/egradle/issues/269 . See my thoughts about it inside issue.

**Comment by paulvi** [comment]
close as duplicate
