### ISSUE TITLE
New project wizard should have selectable version of gradle to be used (or be a Preference option for that)

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#301]
Currently new project defaults to 3.5 (and 3.5 is not even in Preferences, where does it come from? )

![](https://user-images.githubusercontent.com/1614482/31237410-7948ca98-aa29-11e7-84df-7c954c542d4d.png)

**Comment by de-jcup** [comment]
Currently the version is simply fix inside the template _gradle-wrapper.properties of template "gradle-wrapper" which is used by all projects:

`distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-bin.zip`

It's a good idea to make this configurable too. But if the user setup e.g. "never" or "2335.0" it is its own fault that this gradle verision does not exist at all! Ther wil be a failure inside the initial creation...
