### ISSUE TITLE
EGradle Preference page should have link to this project main URL

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#302]
EGradle Preference page should have link to this project main URL,
so that users who got Editor, can easily navigate to this project page to learn more.

![image](https://user-images.githubusercontent.com/1614482/31238158-9d9580e2-aa2b-11e7-81cf-10b67fb55b75.png)

**Comment by de-jcup** [comment]
When you only got the editor, you will have only:

Preferences->
    EGradle->
      Editor...

And nothing more. So why should I introduce here a link? And if so where should it go?

**Comment by paulvi** [comment]
What is mean is clickable links to be open in browser, like done at https://github.com/jeeeyul/eclipse-themes/

![](https://github.com/jeeeyul/eclipse-themes/wiki/images/customize.png)

See GitHub and Marketplace links.

**Comment by de-jcup** [comment]
okay. got it.

**Comment by paulvi** [comment]
90% users don't even know plugin name once it is installed into IDE.

Now that Editor included into Gradle IDE Pack #311 with this issue, users have more chance to now what they are using.

**Comment by de-jcup** [comment]
Looks now:

![image](https://user-images.githubusercontent.com/11644753/31758131-73d70e2a-b4ac-11e7-919c-919a44dc7695.png)

The link goes directly to https://github.com/de-jcup/egradle/wiki
