### ISSUE TITLE
Simple project should be default

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#303]
Just first screen for references

![image](https://user-images.githubusercontent.com/1614482/31238322-34b845e0-aa2c-11e7-8106-2e66db7addb1.png)

Simple project should be default. Usually users create much more simple projects.

![image](https://user-images.githubusercontent.com/1614482/31238329-39972f5e-aa2c-11e7-91eb-058de1bac7c1.png)

**Comment by de-jcup** [comment]
Inside templates a new key is defined now :"priority". The lowest value is now the default selection. Its also the ordering of templates inside wizard selection.

With #313 the basic template was introduced. This template has now the lowest priority treshold and is so now the default. Users are able to change the behaviour by changing the templates.
