### ISSUE TITLE
Get support within Spring IDE dialog

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#304]
It would help a lot for promotion of this project to be as option within Spring IDE

![image](https://user-images.githubusercontent.com/1614482/31238619-17e22d54-aa2d-11e7-994c-7099ac04be8f.png)

**Comment by de-jcup** [comment]
Sorry not enough time - will close this issue.

**Comment by de-jcup** [comment]
Sorry not enough time - will close this issue.
