### ISSUE TITLE
Too many .gradle files in new EGradle project

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#305]
![image](https://user-images.githubusercontent.com/1614482/31238837-b464dc8a-aa2d-11e7-8922-54033d2264cb.png)

There are 6 .gradle files, that is confusing for new Gradle user (even though the may be good reason and temple)

Also `settings.gradle` should not be there at all.

Maybe do new 3rd option for new project wizard as New Gradle project
as rename existing as "New Gradle project with gradle templates"? ...

**Comment by de-jcup** [comment]
Hello @paulvi, 

As you can read inside [documentation ](https://rawgit.com/de-jcup/egradle/master/egradle-plugin-main/html/user_guide/new_project_wizard.html#custom_templates) you are able to write own templates.

If you would write a 
"Basic single gradle project (Java)" template

and give me a patch I will add it to the next release.

I would also invite you to write a template for Android 
e.g.
"Basic single gradle project (Android)" ?

**Comment by paulvi** [comment]
"Basic single gradle project (Java)" template is #313 

"Basic single gradle project (Android)" should actually be Android with Eclipse ADT project,
as Android Studio uses multimodule project structure.

https://stackoverflow.com/questions/20801042/how-to-create-android-project-with-gradle-from-command-line

**Comment by de-jcup** [comment]
With #313 an own template was created. So closing this issue
