### ISSUE TITLE
disable virtual project (add related icons) for simple project

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#306]
First I think the whole idea of having virtual project is confusing.

Then for simple project created, I try "Update or create virtual project"
it gives me some magic EGradle  in some magic .egradle folder, 
that is not even seen in Eclipse IDE with hidden files shown (my personal default)

![image](https://user-images.githubusercontent.com/1614482/31239551-0c78024c-aa30-11e7-8421-76041a77f18e.png)

P.S. I found .egradle folder in file system, but why should I leave IDE for that?

![image](https://user-images.githubusercontent.com/1614482/31239687-96c891a0-aa30-11e7-9733-83a73462bf01.png)

**Comment by de-jcup** [comment]
The virtual root project is only relevant for people which using package explorer and want to have the root parts also visible. Its an absolute optional feature and helped me and many other people many times.

When you import a structure like 

/
/my-eclipse-project1
/my-eclipse-project2
/somethin-else

by 
gradlew eclipse

and then "import existing projects"

you see only 
my-eclipse-project1, my-eclipse-project2 but not content insisde / or /something-else

The featuer is full described at 
https://rawgit.com/de-jcup/egradle/master/egradle-plugin-main/html/user_guide/virtual_root_project.html
or in delived eclipse help.

I and many others use this feature many times, so it is necessary.

It makes no sense for simple projects - that's true

**Maybe for simple projects the button should be gray?**

**Comment by paulvi** [comment]
Yes, definitely virtual project for simple project should be disable, as it have produced confusing result.

**Comment by paulvi** [comment]
I usually just create General project
