### ISSUE TITLE
Toolbar icons should be sorted by first-to-be-used rule

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#307]
Toolbar icons should be sorted by first-to-be-used rule:  

e.g. create new - execute task - update dependencies - get JUnit results ...

![image](https://user-images.githubusercontent.com/1614482/31239835-122dc7ca-aa31-11e7-94d3-89f0735ef28c.png)

Currently New is the last option.

**Comment by de-jcup** [comment]
Already done with f5fb5e6f194929ed343ee578189312847b43f408

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/36346900-3bc3b9aa-1449-11e8-845b-66a39942cbbc.png)
