### ISSUE TITLE
Notification: EGradle Editor is included into Gradle IDE Pack

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#311]
EGradle Editor is included into Gradle IDE Pack https://marketplace.eclipse.org/content/gradle-ide-pack for Oxygen+

announced at http://www.nodeclipse.org/#news

I cannot find quickly ticket, where I asked make Editor independently installable feature. Now it is. Thank you. And I hold my word. Excuse me that it was a bit later, than it could be.

**Comment by de-jcup** [comment]
Hello @paulvi , you are welcome and thank you too! 
It's very nice that EGradle Editor is now used in another IDE too. 

_By the way: The origin issue was #136 ._

greez Albert
