### ISSUE TITLE
New project template for Eclipse ADT

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#316]
From #305 put into own issue:

"Basic single gradle project (Android)" should actually be Android with Eclipse ADT project,
as Android Studio uses multimodule project structure.

https://stackoverflow.com/questions/20801042/how-to-create-android-project-with-gradle-from-command-line

**Comment by paulvi** [comment]
Related gradle plugin https://github.com/greensopinion/gradle-android-eclipse

**Comment by de-jcup** [comment]
What do you think about the plugin - how much stable do you think it is?

**Comment by paulvi** [comment]
Not using. Not doing Android development for last 2 years.

**Comment by de-jcup** [comment]
Having no time for this . Will close it
