### ISSUE TITLE
EGradle & "Minimalist Gradle Editor"

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#32]
from #18 

> Maybe EGradle could use your "Minimalist Gradle Editor" instead of an own implementation (which is still very alpha). But there are some feature I would like to integrate into EGradle (e.g. hyperlinking, code template mechanism, auto completion etc.) which are not supported.

I am for saving energy and human effort. Can you take Minimalist Gradle Editor?
Either way end users could have choice. 

My initial goal was make it fit for Android, but as Groovy-Eclipse https://github.com/groovy/groovy-eclipse (together with Groovy) went off SpringSource backing, it became good for any gradle project.

I wanted it not depend on Groovy, even went to make own parser. Dream finish Outline and make launching task from Outline, at that point it would not be really minimalist.
Now it is https://github.com/Nodeclipse/GradleEditor

**Comment by de-jcup** [comment]
I think you are right. You have been working on the editor a long time now and I think it's better to use your implementation instead to implement an own editor by myself.

Hmm... I do not know exactly how to include your editor project inside my releases.
Should I make a fork of your editor project and put it on my build into the feature project?
How would you integrate an external plugin into your project ? Any ideas are welcome...

**Comment by de-jcup** [comment]
I made a decision: EGradles will still have its own editor. The user has the choice to switch to "Minimalistic Gadle Editor". Having an own editor gives me the chance to integrate the editor a little bit more into EGradle - e.g. for linking etc.

**Comment by paulvi** [comment]
sure, at some point user will want to launch task from Outline, at which point the Editor is not minimalistic anymore.
