### ISSUE TITLE
Try-Catch-Block and closures without { are breaking outline

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#321]
at https://github.com/de-jcup/eclipse-jenkins-editor/issues/20 a problem was described but the problem is an egradle issue so created this:

See  https://github.com/jenkinsci/pipeline-examples/blob/6f1f8770304d25b1f02ad97170bb917982f2c33a/jenkinsfile-examples/nodejs-build-test-deploy-docker-notify/Jenkinsfile
for an example code

It is not the #!groovy which makes the problems but the missing {} and also the try-catch block in combination.

Try-Catch-Blocks and also closures without { should also be contained in outline

**Comment by de-jcup** [comment]
After building a full groovy antlr outline I got following result:

![image](https://user-images.githubusercontent.com/11644753/32613416-27b2b3e4-c56b-11e7-8863-9003e640fac1.png)

So groovy does only use those setup as normal expressions and not as closures (of course the bracket is missing...)

So this should be the same code as only:
```
stage 'Checkout'
checkout scm
stage 'Test'
env.NODE_ENV = "test"
print "Environment will be : ${env.NODE_ENV}"

```
so is only doing
set stage 'checkout'
do checkout...
...
serial.

The outline in egradle and also in jenkinseditor will only show up mehod calls having closures iside

So I will NOT fix the "not closure" handling - at least not in Groovy default outline model

Another option is the "try-catch" block. Using a try catch block should not appear inside a normal groovy outline, because the try-catch should be always inside a method.

So do not implement this for the standard groovy outline as well.

**Comment by paulvi** [comment]
adding in README/docs that some special case is not supported (and user should use `{}`) would be enough.

**Comment by paulvi** [comment]
At current https://github.com/jenkinsci/pipeline-examples/blob/master/jenkinsfile-examples/nodejs-build-test-deploy-docker-notify/Jenkinsfile  version, there is use of `{}`.
Also look at https://github.com/jenkinsci/pipeline-examples/commit/68da48f59579be36ea84454da7685d08f61ef9b6

So it maybe that it is also required for newer version to use `{}`

**Comment by de-jcup** [comment]
This is still a non declarative variant , because of try catch... 

I will do some documentation about supporting only declarative variant

**Comment by paulvi** [comment]
ref https://github.com/de-jcup/eclipse-jenkins-editor/issues/21
