### ISSUE TITLE
Albert Tregnaghi (Editors) Plugins Pack

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#334]
I would like to be able (and enable others) to install all 4 Editors in one step, by adding marketplace entry.
Before I added as IDE packs, but this set of 4 would be better to be named by author,
and they are already likely to be in the same repo, at least on the same host.

So are you OK? How to name? (some people are shy, but there is already good set)

Related links
- https://marketplace.eclipse.org/user/atregnaghi/listings
- https://marketplace.eclipse.org/content/gradle-ide-pack
- https://marketplace.eclipse.org/content/color-ide-pack
- https://marketplace.eclipse.org/content/polyglot-maven-atom-groovy-yaml-ide-pack-bleeding-edge
- https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup

P.S. Maybe it would be nice to include other common Editors like
YML, CSV etc that are not in default Eclipse IDE

**Comment by paulvi** [comment]
P.P.S. or possibly it should be EGradle Full Pack or Build Pack

**Comment by de-jcup** [comment]
I am not sure how you are creating those "Plugins packs".

Are you just creating another marketplace site  and add multiple solutions and their existing update sites ?
If so what happens to the marketplace statistics etc. ? Leads this to a fragmentation? Currently I know (hopefully) that many developers use my tools. 

Could you please explain how those "Plugin packs" are created?

**Comment by paulvi** [comment]
If using Eclipse feature to group plugins, then the set would be fixed, with no opt-out.
So I just went with one more marketplace entry, where every feature/plugin can be selected/deselected during install.
Of course in any case, the plugins must in the same update site (for example composite)

Yes, there will be fragmentation on Marketplace, when Packs would be eating part of separate entries.
But if look at ,say, bintray statistics, it would not matter with way plugins are installed. Maybe even without marketplace client at all.

The most important is convenience to end users. That is quicker install.  

MP entry example - listing features IDs

![image](https://user-images.githubusercontent.com/1614482/35956872-3359c926-0cd3-11e8-89b9-0e5a0eecda96.png)

**Comment by paulvi** [comment]
Or maybe add all Editors to Gradle IDE https://marketplace.eclipse.org/content/egradle-ide
as "Optional - Not Selected"

**Comment by de-jcup** [comment]
Hello @paulvi ,

I am thinking about your suggestion. 
Maybe I will provide a (extra or in EGradle IDE?) composite site as described by Lars Vogel at
http://blog.vogella.com/2010/04/06/eclipse-p2-composite-repository/ 
+ your "Optional - Not Selected" approach on the marketplace...

So I would be able to reuse the existing (different) bintray repositories by ONE composite.

(In next comment I will propose a complete different approach by extending the eclipse marketplace... please read and give me feedback about my idea)

**Comment by de-jcup** [comment]
@paulvi , I appreciate your idea of having a place for other users to install some group of cool plugins by one single click - convenience and nice. What I am not happy about is the fragmentation of favorites, install metrics etc. (bintray supports only 30 day metrics for free...)

I would suggest another approach - maybe this could be done in future...: 
The best way (IMHO) would be to extend the Favorite feature from eclipse marketplace (client). Currently You can install ALL Favorites of another marketplace provider by one click by MPC client.

When this approach would be extended in a way where other users could group existing solutions to cool bundles they like and users could just use those by one click and have all installed, then community could share and create those bundles without any work for plugin developers and the marketplace metrics /favorites etc. would not be fragmented in any way - because they would just reuse the existing solutions. 

Maybe I could mention the idea at eclipse.org bugzilla. What do you think about my idea?

1. Favorites of one member can already be installed

**Comment by paulvi** [comment]
If you are curious about metrics, think about usage metrics (How many time launched, how long is session, what OS, Java version etc) #335

Also a new way to install plugins, should be different issue.
Eclipse already has too many: update site, copy to dropins folder, MPC, MPC dran-n-drop, p2f file and the last fileExtension association.  
MPC currently requires the least number of clicks, i.e. quicker for end user.  
I don't think "you need to select other tab to use this way" would work,

Yes, composite repository is the first and most important step.  
That would make direct using of update site also comfortable (Help -> Install New Software)  
You and users would want shorter URL (easier to remember), but that again leads to question "How do you name the bigger set of plugins?"

**Comment by de-jcup** [comment]
I think "jcup plugins" or"de-jcup plugins" would be nice and easy to remember.

I always use de.jcup as start of my packages, its my github name and I am also the owner of "jcup.de" namespace in web.

**Comment by paulvi** [comment]
One more reason why a pack can be good:

When installing EGradle, Jenkins Editor is to be uninstalled. I guess because of shared dependencies, and Eclipse cannot resolve to update Jenkins Editor

![image](https://user-images.githubusercontent.com/1614482/39160828-21ce9bc0-47a0-11e8-88f4-1d37e5c80664.png)

**Comment by de-jcup** [comment]
Hm.. okay. I will create an entry at marketplace

**Comment by de-jcup** [comment]
I started https://github.com/de-jcup/jcup-eclipse-plugins-collection

**Comment by de-jcup** [comment]
closing this issue - see progress at https://github.com/de-jcup/jcup-eclipse-plugins-collection/issues/1
