### ISSUE TITLE
Launcher with empty tasks gives an error instead of using defaultTasks

### ISSUE THREAD

**Issue by jlczuk** [de-jcup/egradle#363]
When I run a launch configuration with no tasks specified, the build gives me the error:
FAILURE: Build failed with an exception.

* What went wrong:
Task '' not found in root project 'testProject'

Wouldn't it make more sense to run it with no tasks and let Gradle use the script's defaultTasks?

**Comment by de-jcup** [comment]
Similar to #364 , so should implement together.
