### ISSUE TITLE
Empty quicklanch task should run gradle with defaultTasks instead of dismissing

### ISSUE THREAD

**Issue by jlczuk** [de-jcup/egradle#364]
If I want to dismiss the dialog, I can press ESC.  The current implementation won't allow me to run my build script's defaultTasks because pressing enter on quick launch with not tasks also dismisses the dialog.

I would like to see quick dialog do this:
1) If enter is pressed and no tasks were entered, run gradle without a task specification and let it use the defaultTasks of the build.
2) If I press ESC, dismiss the dialog (like it already does).

**Comment by de-jcup** [comment]
I appreciate your idea. I put it on then next milestone - but I am currently doing a lot of stuff on other sites and I am not sure when it will come up.

**Comment by jlczuk** [comment]
I will close this since it is basically a duplicate of the other one.  You understand the expected behavior.  This is not urgent, just an annoyance.  Thank you for considering to work on it.
