### ISSUE TITLE
Don't add closing brakes if within string

### ISSUE THREAD

**Issue by BeckerFrank** [de-jcup/egradle#389]
This was reported in https://github.com/de-jcup/eclipse-jenkins-editor/issues/60 but need a fix in file /egradle-plugin-main/src/main/java-eclipse/de/jcup/egradle/eclipse/ui/GroovyBracketInsertionCompleter.java

**Comment by de-jcup** [comment]
@BeckerFrank : Thank you for the fix and apologizes for the late response.
