### ISSUE TITLE
Promoting

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#49]
# Wikipedia
- [x] Make an entry for EGradle (de) https://de.wikipedia.org/wiki/EGradle
- [x] Make an entry for EGradle (en)
- [x] Rename english version (Egradle to EGradle)
- [ ] retry wikipedia with "eclipse software category" as suggested by @paulvi

# YouTube
## Common
- [x] Add channel EGradle
  https://www.youtube.com/channel/UCvzi4jCPdEw-u6x1WwdKoLA
- [x] Make Playlist "tutorial"
  https://www.youtube.com/playlist?list=PLnO8pgGpD7DlvsszAIjM26_2_0B9VJV4n
## 0.7.3
- [x] Video: installation 0.7.3
- [x] Video: setup and import multiprojects 0.7.3
## 1.0.2
- [ ] Video: egradle import wizard
- [x] Video: help documentation
- [ ] Video: launching
- [x] Video: junit integration
- [x] Video: outline 
- [x] Video: parse errors
- [x] Video: compile errors at launch time
## 1.1.0
- [x] Video: CTRL+SHIFT+P
- [x] Video: Link to other gradle files
- [x] Video: quick outline 

## 1.2.0
- [ ] Video: auto derive

## 1.3.0
- [ ] Video: show refresh eclipse icon usage
- [x] Video: code completion
- [ ] Video: CTRL +7
- [ ] Video: tooltips
- [ ] Video: automatic curly bracket closing
- [ ] Video: show dependencies
- [ ] Video: show simply link to java or groovy resource files

## 2.0.0
- [ ] Video: New project wizard

# StackOverflow
Search for stackoverflow entries  - if there are developers needing a better/simpler gradle integration give a hint about egradle.
   - [x] Answered at http://stackoverflow.com/questions/6442619/launching-gradle-builds-from-eclipse/40970036#40970036

# Wrong discussed articles about EGradle
- [ ] EGradle was wrong tested and described at https://www.selikoff.net/2017/01/14/gradle-in-eclipse-egradle-vs-buildship/ must be answered/corrected. E.g: Author should do a build and a simple refresh before complaining about missing build folders...

# Other
- [x] fileExtension_gradle as described by @paulvi in #116

**Comment by paulvi** [comment]
lonely pages like https://en.wikipedia.org/wiki/EGradle can be deleted automatically

add the page to "Eclipse plugins" category
like on https://en.wikipedia.org/wiki/Nodeclipse

**Comment by de-jcup** [comment]
hmm.. the wikipedia group members are always a little bit "angry" when they smell "product placements" in there. Maybe I give it a nother try with your proposal. Anyway , thanks!

**Comment by paulvi** [comment]
well, objective wikipedia article should list all plugins.

**Comment by de-jcup** [comment]
Sorry not enough time - will close this issue.
