### ISSUE TITLE
Sign Plugins/Features for marketplace

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#59]
The egradle feature is always prompted as "unsigned content..." so it wourld be more userfriendly and secure to handle this correctly.

**Comment by de-jcup** [comment]
https://nirmalsasidharan.wordpress.com/2010/09/04/signing_eclipse_plugins/
Describes it ...

**Comment by paulvi** [comment]
well, in reality Eclipse is asking "do you trust this .." instead of warning "some plugins are not signed".

And that dialogue is not often seen by users.
