### ISSUE TITLE
Enable eclipse egradle code to be build by gradle

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#84]
There are many parts of egradle which are not automatically tested.

To test also eclipse based parts the dependencies are necessary to be "gradleized".

**Comment by de-jcup** [comment]
https://github.com/akhikhl/wuff

https://plugins.gradle.org/plugin/org.akhikhl.wuff.eclipse-bundle

**Comment by paulvi** [comment]
Eclipse Buildship and other project are fully built by gradle.

There should automatic build to produce update site

**Comment by de-jcup** [comment]
In https://github.com/eclipse/buildship/blob/master/build.gradle the build file can be found. The buildship team seems to do a great job here, but the build is no simple "out of the box by gradle plugin" approach.

@paulvi - would you like to investigate the build mechanism of buildship and try to write a update-site.gradle file containing a task which does the job? I am too much busy to do this by my own.
